package pyxis.uzuki.live.richutilskt.demo.item

import java.io.Serializable

/**
 * RichUtilsKt
 * Class: CategoryItem
 * Created by Pyxis on 2017-11-06.
 *
 * Description:
 */

enum class CategoryItem : Serializable {
    ALERT, ASSETS, BITMAP, CLIPBOARD, CONTACT, DATE, DEVICEID, DIMEN, DRAWABLE, FILE, FONT, INFLATER,
    JSON, KEYBOARD, KEYHASH, NETWORK, PERMISSION, PHOTO, PICKMEDIA, PREFERENCE, PROCESS, REBOOT, STATUSBAR,
    STREAM, SYSTEMSERVICE, TEXT, UNREAD, VERSION, THUMBNAIL, VIBRATE, VIEW, CENTERICON, COMBINED, HTMLTEXTVIEW, INTENT,
    THREAD, CRASH, INAPP, LOCATION
}